# Generated by Django 5.2.17 on 2026-10-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('instruments', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fill_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source', models.CharField(default='broker', max_length=32)),
                ('filled_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('allocated_qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('fill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='trading.fill')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_order_id', models.CharField(max_length=128, unique=True)),
                ('broker_order_id', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(choices=[('broker', 'Real Broker API (Alpaca MOC)'), ('simulated_manual', 'Simulated Manual (LatestQuote + Telegram)'), ('simulated_paper', 'Simulated Paper App (Official Close)')], default='broker', max_length=32)),
                ('order_type', models.CharField(default='moc', max_length=16)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='submitted', max_length=16)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokers.brokeraccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='portfolios.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fill',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='trading.order'),
        ),
        migrations.CreateModel(
            name='OrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('net_delta_qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokers.brokeraccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='trading.orderintent'),
        ),
        migrations.CreateModel(
            name='RebalanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled Daily Window'), ('allocation_change', 'Allocation Weight Change'), ('signal_change', 'Signal Change'), ('periodic', 'Periodic Calendar Rebalance'), ('manual', 'Manual User / Operator Trigger')], default='scheduled', max_length=32)),
                ('as_of', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('executing', 'Executing'), ('done', 'Done'), ('failed', 'Failed'), ('missed_cutoff', 'Missed Cutoff')], default='planned', max_length=16)),
                ('equity_base', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('prices', models.JSONField(blank=True, default=dict)),
                ('decisions', models.JSONField(blank=True, default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalance_runs', to='portfolios.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderintent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='trading.rebalancerun'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sleeve_capital', models.DecimalField(decimal_places=2, max_digits=16)),
                ('target_qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('current_qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('delta_qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('reason', models.CharField(default='drift', max_length=128)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokers.brokeraccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trading.rebalancerun')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
