# Generated by Django 5.2.17 on 2026-10-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('alpaca', 'Alpaca'), ('manual', 'Manual Broker')], default='manual', max_length=32)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('paper', 'Paper')], default='live', max_length=16)),
                ('execution_mode', models.CharField(choices=[('auto', 'Auto (API / MOC)'), ('manual', 'Manual (Simulated Quote + Telegram alert)')], default='manual', max_length=16)),
                ('display_name', models.CharField(max_length=128)),
                ('broker_label', models.CharField(default='eToro', help_text='e.g. eToro, Alpaca, Interactive Brokers', max_length=64)),
                ('external_account_id', models.CharField(blank=True, max_length=64)),
                ('managed_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('commission_model', models.JSONField(blank=True, default=dict)),
                ('order_policy', models.JSONField(blank=True, default=dict)),
                ('trading_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('alpaca', 'Alpaca'), ('manual', 'Manual Broker (eToro, IBKR, etc.)')], default='alpaca', max_length=32)),
                ('environment', models.CharField(choices=[('live', 'Live Trading'), ('paper', 'Paper / Sandbox Trading')], default='paper', max_length=16)),
                ('auth_type', models.CharField(default='api_key', max_length=32)),
                ('secret_encrypted', models.BinaryField()),
                ('key_fingerprint', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
