# Generated by Django 5.2.17 on 2026-10-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('family', models.CharField(db_index=True, default='General', max_length=64)),
                ('kind', models.CharField(choices=[('signal_single', 'Single Signal Strategy'), ('signal_multi', 'Multi Signal Combined Strategy'), ('cross_asset', 'Cross Asset Strategy'), ('follow_price', 'Follow Price Strategy'), ('macro_signal', 'Macro Signal Only')], default='signal_single', max_length=32)),
                ('engine', models.CharField(default='single_signal', max_length=64)),
                ('timeframe', models.CharField(default='1d', max_length=16)),
                ('decision_offset_minutes', models.PositiveIntegerField(default=25)),
                ('rebalance_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly (Last business day)'), ('monthly', 'Monthly (Last business day)'), ('quarterly', 'Quarterly (Last business day)'), ('never', 'Never / Signal Trigger Only')], default='daily', max_length=32)),
                ('rebalance_tolerance', models.DecimalField(decimal_places=4, default=0.1, max_digits=7)),
                ('rebalance_tolerance_mode', models.CharField(choices=[('relative', 'Relative Drift'), ('absolute', 'Absolute Drift')], default='relative', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('signal_only', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('params_schema', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paper', 'Paper'), ('live', 'Live'), ('retired', 'Retired')], default='live', max_length=16)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('strategy', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('as_of', models.DateTimeField(db_index=True)),
                ('target_exposure', models.DecimalField(decimal_places=4, max_digits=7)),
                ('changed', models.BooleanField(default=False)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategies.strategyversion')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_slug', models.CharField(max_length=64)),
                ('instruments', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000.0, max_digits=16)),
                ('rebalance_override', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('traded', 'Traded Asset'), ('signal_source', 'Signal Source Asset')], default='traded', max_length=16)),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=7)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='strategies.strategyversion')),
            ],
            options={
                'unique_together': {('version', 'instrument', 'role')},
            },
        ),
    ]
