# Generated by Django 5.2.17 on 2026-10-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='rebalance_frequency',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='rebalance_tolerance',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='rebalance_tolerance_mode',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='kind',
            field=models.CharField(choices=[('one_strategy', 'One Strategy Bot'), ('multi_strategy', 'Multi Strategy Bot'), ('cross_asset', 'Cross Asset Bot'), ('follow_price', 'Follow Price Bot'), ('signal_dollar', 'Signal Dollar (Macro)'), ('signal_options', 'Signal Options (Macro)')], default='one_strategy', max_length=32),
        ),
    ]
