# Generated by Django 5.2.17 on 2026-10-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_remove_strategy_rebalance_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='kind',
            field=models.CharField(choices=[('one_strategy', 'One Strategy Bot'), ('multi_strategy', 'Multi Strategy Bot'), ('cross_asset', 'Cross Asset Bot'), ('ranked_allocation', 'Ranked Allocation Bot (Metrics)')], default='one_strategy', max_length=32),
        ),
        migrations.CreateModel(
            name='AllocationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('as_of', models.DateTimeField(db_index=True)),
                ('weights', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_snapshots', to='strategies.strategyversion')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
    ]
