# Generated by Django 5.2.17 on 2026-10-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_alter_strategy_kind_allocationsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='kind',
            field=models.CharField(choices=[('one_strategy', 'One Strategy Bot'), ('multi_strategy', 'Multi Strategy Bot'), ('cross_asset', 'Cross Asset Bot'), ('ranked_allocation', 'Ranked Allocation Bot (Metrics)'), ('hold', 'Hold & Reserve Bot'), ('smart_accumulator', 'Smart Accumulator Bot')], default='one_strategy', max_length=32),
        ),
    ]
