# Generated by Django 5.2.17 on 2026-10-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('asset_class', models.CharField(choices=[('etf', 'ETF'), ('equity', 'Equity / Stock'), ('index', 'Index'), ('crypto', 'Crypto')], default='etf', max_length=32)),
                ('tradable', models.BooleanField(default=True)),
                ('fractionable', models.BooleanField(default=True)),
                ('shortable', models.BooleanField(default=False)),
                ('yahoo_symbol', models.CharField(blank=True, max_length=32)),
                ('alpaca_symbol', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
