# Generated by Django 5.2.17 on 2026-10-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('brokers', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerpositionsnapshot',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='brokerpositionsnapshot',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
    ]
