# Generated by Django 5.2.17 on 2026-10-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('brokers', '0001_initial'),
        ('instruments', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitysnapshot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_snapshots', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='broker_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='logicalposition',
            name='broker_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='logicalposition',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
        migrations.AddField(
            model_name='logicalposition',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logical_positions', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='logicalposition',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='sleevepnldaily',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_pnls', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='sleevepnldaily',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy'),
        ),
        migrations.AlterUniqueTogether(
            name='equitysnapshot',
            unique_together={('portfolio', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='logicalposition',
            unique_together={('portfolio', 'broker_account', 'strategy', 'instrument')},
        ),
        migrations.AlterUniqueTogether(
            name='sleevepnldaily',
            unique_together={('portfolio', 'strategy', 'date')},
        ),
    ]
