# Generated by Django 5.2.17 on 2026-10-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=16)),
                ('status', models.CharField(default='ok', max_length=16)),
                ('calls_used', models.PositiveIntegerField(default=0)),
                ('statements_saved', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundamentalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('Q', 'Quarter'), ('FY', 'Fiscal Year')], default='Q', max_length=2)),
                ('period_end', models.DateField(db_index=True)),
                ('available_at', models.DateField(blank=True, db_index=True, help_text='Fecha de publicación (filing). Si falta se estima period_end + 45 días.', null=True)),
                ('source', models.CharField(choices=[('fmp', 'FMP'), ('eodhd', 'EODHD'), ('yfinance', 'yfinance')], max_length=16)),
                ('data', models.JSONField(default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('instrument', 'period_type', 'period_end')},
            },
        ),
    ]
