# Generated by Django 5.2.17 on 2026-10-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('live', 'Live (Real Money)'), ('paper', 'Paper (Simulated)'), ('sandbox', 'Sandbox (Staff Broker Paper)')], default='paper', max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=16)),
                ('trading_enabled', models.BooleanField(default=True)),
                ('max_gross_allocation', models.DecimalField(decimal_places=4, default=1.0, max_digits=7)),
                ('paper_initial_capital', models.DecimalField(decimal_places=2, default=100000.0, max_digits=16)),
                ('paper_commission_model', models.JSONField(blank=True, default=dict)),
                ('rebalance_pending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_weight', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(default='moderate', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_weight', models.DecimalField(decimal_places=4, max_digits=7)),
                ('enabled', models.BooleanField(default=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokers.brokeraccount')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyversion')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_weight', models.DecimalField(decimal_places=4, max_digits=7)),
                ('new_weight', models.DecimalField(decimal_places=4, max_digits=7)),
                ('source', models.CharField(choices=[('user', 'User Request'), ('recommended_follow', 'Follow Recommended Portfolio'), ('admin', 'Admin Override')], default='user', max_length=32)),
                ('effective_at', models.DateTimeField()),
                ('applied', models.BooleanField(default=False)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
