# Generated by Django 5.2.17 on 2026-10-03 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationchange',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_changes', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='recommendedallocation',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='recommendedallocation',
            name='recommended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolios.recommendedportfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='follows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.recommendedportfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('portfolio', 'strategy')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendedallocation',
            unique_together={('recommended', 'strategy')},
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'live'), models.Q(('status', 'closed'), _negated=True)), fields=('user',), name='one_live_portfolio_per_user'),
        ),
    ]
