# Generated by Django 5.2.17 on 2026-10-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='rebalance_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly (Last business day)'), ('monthly', 'Monthly (Last business day)'), ('quarterly', 'Quarterly (Last business day)'), ('never', 'Never / Signal Trigger Only')], default='daily', max_length=32),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rebalance_tolerance',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=7),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rebalance_tolerance_mode',
            field=models.CharField(choices=[('relative', 'Relative Drift'), ('absolute', 'Absolute Drift')], default='relative', max_length=16),
        ),
        migrations.AddField(
            model_name='recommendedportfolio',
            name='rebalance_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly (Last business day)'), ('monthly', 'Monthly (Last business day)'), ('quarterly', 'Quarterly (Last business day)'), ('never', 'Never / Signal Trigger Only')], default='monthly', max_length=32),
        ),
        migrations.AddField(
            model_name='recommendedportfolio',
            name='rebalance_tolerance',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=7),
        ),
        migrations.AddField(
            model_name='recommendedportfolio',
            name='rebalance_tolerance_mode',
            field=models.CharField(choices=[('relative', 'Relative Drift'), ('absolute', 'Absolute Drift')], default='relative', max_length=16),
        ),
    ]
