# Generated by Django 5.2.17 on 2026-10-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_quote', to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=16)),
                ('high', models.DecimalField(decimal_places=6, max_digits=16)),
                ('low', models.DecimalField(decimal_places=6, max_digits=16)),
                ('close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='instruments.instrument')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('instrument', 'date')},
            },
        ),
    ]
